version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: login_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node-app:
    build: 
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
