version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: login_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 3

  node-app:
    build: 
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/hello"]
      interval: 10s
      timeout: 5s
      retries: 3

  tester:
    image: curlimages/curl
    depends_on:
      node-app:
        condition: service_healthy
    command: >
      sh -c "curl -sSf http://node-app:3000/hello"

volumes:
  mysql_data:
